### ISSUE TITLE
Empty pages after deleting a bookmark

### ISSUE THREAD

**Issue by Hase024** [senekor/buenzlimarks#132]
After deleting a bookmark, all widgets on all pages disappear. After reload of the bokkmarks page, everything is ok. All bookmarks and widgets are back, just the deleted is gone.

**Comment by senekor** [comment]
I think this might be a difficult bug to fix. @Robrisi let's do this together some time.

**Comment by senekor** [comment]
Removed the requirement label, because it's a bug report.

**Comment by senekor** [comment]
This was fixed by #141. 

The redux state pattern itself wasn't the fix, but it and the fix went hand-in-hand.

The problem was that widgets and bookmarks would rerender themselves reactively when they changed. Including when they were _deleted_. This meant a refetch of the data was triggered and sice that widget / bookmark didn't exist anymore, the request failed and the app crashed.

(Error handling is still pretty much non-existent.)

With the fix, widgets and bookmarks don't rerender themselves reactively anymore. The key of these components in the widget / bookmark list is now the entire object itself, as can be seen in [this diff](https://github.com/senekor/buenzlimarks/pull/141/files#diff-caa840d02a4c938e25650e6def501af8115cd31a0e8bc17988da52c175d8e7e5L16-R19). This means the `For` component will render a new widget / bookmark top-down when anything changes. The `For` component then also handles deletions correctly.
